& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "Sebastian" `
  -ModName "Sebastian" `
  -ModFolder "sebastian" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/sebastian/Sebastian-Original.zip" `
  -ModBaseFilesUrlHash "1f3194a280aaef45687d0a4938876209991ae7260dd7d3c1b94ad81395530dcd" `
  -ModReadmePath "readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
